steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate xproperty
      mkdir build
      cd build
      cmake -DDOWNLOAD_GTEST=ON $(Build.SourcesDirectory)
    displayName: Configure xproperty
    workingDirectory: $(Build.BinariesDirectory)
      
  - script: |
      source activate xproperty
      make -j2 test_xproperty
    displayName: Build xproperty
    workingDirectory: $(Build.BinariesDirectory)/build
          
  - script: |
      source activate xproperty
      cd test
      ./test_xproperty
    displayName: Test xproperty
    workingDirectory: $(Build.BinariesDirectory)/build/test
